version: "2"
services: 
    webserver:
        image: izinckevich/pubmed_labeling:latest
        volumes:
            - ./server:/webserver
        command: bash -c "label-studio start ."
        ports: 
            - 8200:8200