version: "3"
services: 
    webserver:
        container_name: webserver
        image: pubmed_labeling:latest
        build: .
        volumes:
            - ./server:/webserver
        command: bash -c "label-studio start ."
        ports: 
            - 8200:8200